
if versioncmp($::puppetversion,'3.6.1') >= 0 {
  $allow_virtual_packages = hiera('allow_virtual_packages',false)
  Package {
    allow_virtual => $allow_virtual_packages,
  }
}

Exec {
	path => ['/usr/local/bin','/usr/bin','/usr/local/sbin','/usr/sbin']
}

File {
	owner => root,
	group => root,
}

# package { [ 'git.x86_64' ]: ensure=>ensure, }
file { '/etc/yum.repos.d/mongodb.repo':
  ensure  => 'file',
  mode    => '644',
  content => "[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1",
}

# augeas { 'yum_mongodb_repo':
#     context => '/etc/yum.repos.d/mongodb.repo',
#     changes => [
#       "set /files/etc/yum.repos.d/mongodb.repo/mongodb/name = 'MongoDB Repository'",
#       "set /files/etc/yum.repos.d/mongodb.repo/mongodb/baseurl = 'http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/'",
#       "set /files/etc/yum.repos.d/mongodb.repo/mongodb/gpgcheck = '0'",
#       "set /files/etc/yum.repos.d/mongodb.repo/mongodb/enabled = '1'",
#     ],
#     require => [ File['/etc/yum.repos.d/mongodb.repo'] ],
# }

package { 'mongodb-org':
 	ensure => present,
  require => [ File['/etc/yum.repos.d/mongodb.repo'] ], # , Augeas['yum_mongodb_repo'] ],
}

# crete the group mongodb
group { 'mongodb':
  ensure => 'present',
  gid    => '1001',
}

# crete the user mongodb
user { 'mongodb':
  ensure           => 'present',
  managehome 	     => true,
  gid              => '1001',
  home             => '/home/mongodb',
  password         => '$6$nD4vMHXv$xlQYJuXUwZ.U0mD/6XmcuC6JmfQAj7hN759SuSMue2I6fePPXbzQChJDhRA3XAyO3YNS9SL50ul0ru/G.PWGE.',
  password_max_age => '99999',
  password_min_age => '0',
  shell            => '/bin/bash',
  uid              => '1001',
  purge_ssh_keys   => true,
  require 		     => [ Group['mongodb'] ],
}

# Note to self: This is a wideopen configuration
# -------------------------------------
# iptables -F
# iptables -X
# iptables -t nat -F
# iptables -t nat -X
# iptables -t mangle -F
# iptables -t mangle -X
# iptables -P INPUT ACCEPT
# iptables -P FORWARD ACCEPT
# iptables -P OUTPUT ACCEPT
# -------------------------------------
file { '/etc/sysconfig/iptables':
  ensure   => 'file',
  mode     => '600',
  content  => "# Generated by iptables-save v1.4.21 on Sun Oct 19 17:24:58 2014
*nat
:PREROUTING ACCEPT [5:772]
:INPUT ACCEPT [5:772]
:OUTPUT ACCEPT [4:288]
:POSTROUTING ACCEPT [4:288]
COMMIT
# Completed on Sun Oct 19 17:24:58 2014
# Generated by iptables-save v1.4.21 on Sun Oct 19 17:24:58 2014
*mangle
:PREROUTING ACCEPT [344:21908]
:INPUT ACCEPT [344:21908]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [196:18936]
:POSTROUTING ACCEPT [196:18936]
COMMIT
# Completed on Sun Oct 19 17:24:58 2014
# Generated by iptables-save v1.4.21 on Sun Oct 19 17:24:58 2014
*security
:INPUT ACCEPT [56650:121032954]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [54546:2346668]
:FORWARD_direct - [0:0]
:INPUT_direct - [0:0]
:OUTPUT_direct - [0:0]
-A INPUT -j INPUT_direct
-A FORWARD -j FORWARD_direct
-A OUTPUT -j OUTPUT_direct
COMMIT
# Completed on Sun Oct 19 17:24:58 2014
# Generated by iptables-save v1.4.21 on Sun Oct 19 17:24:58 2014
*raw
:PREROUTING ACCEPT [57113:121142193]
:OUTPUT ACCEPT [54546:2346668]
:OUTPUT_direct - [0:0]
:PREROUTING_direct - [0:0]
-A PREROUTING -j PREROUTING_direct
-A OUTPUT -j OUTPUT_direct
COMMIT
# Completed on Sun Oct 19 17:24:58 2014
# Generated by iptables-save v1.4.21 on Sun Oct 19 17:24:58 2014
*filter
:INPUT ACCEPT [338:21632]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [191:18556]
COMMIT
# Completed on Sun Oct 19 17:24:58 2014",
}

# create the home directory for mongodb
file {'/home/mongodb':
	ensure  => 'directory',
	group   => 'mongodb',
	owner   => 'mongodb',
	mode    => '755',
	require => [ Group['mongodb'], User['mongodb'] ],
}

# Add hosts to the /etc/host file ##
augeas { 'etc_hosts':
  context => '/etc/hosts',
  changes => [
    "set /files/etc/hosts/1/ipaddr 127.0.0.1",
    "set /files/etc/hosts/1/canonical localhost",
    "set /files/etc/hosts/1/alias localhost.localdomain",
    "set /files/etc/hosts/2/ipaddr ::1",
    "set /files/etc/hosts/2/canonical localhost",
    "set /files/etc/hosts/2/alias ipv6-loopback",
    "set /files/etc/hosts/3/ipaddr 192.168.33.10",
    "set /files/etc/hosts/3/canonical mongodbserver",
  ],
}